"""Create chatbots table - fixed

Revision ID: 8010689b494d
Revises: 72bc4607187b
Create Date: 2025-06-06 14:10:21.021168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8010689b494d'
down_revision: Union[str, None] = '72bc4607187b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chatbot_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.chatbot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_files_chatbot_id'), 'chatbot_files', ['chatbot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_files_chatbot_id'), table_name='chatbot_files')
    op.drop_table('chatbot_files')
    # ### end Alembic commands ###
