"""empty message

Revision ID: db9bdaa46705
Revises: 77f11fd89301
Create Date: 2025-06-06 15:34:24.722280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db9bdaa46705'
down_revision: Union[str, None] = '77f11fd89301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('timestamp', sa.DateTime(), nullable=False))
    op.drop_column('chat_messages', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('chat_messages', 'timestamp')
    # ### end Alembic commands ###
